export const PerformanceLedgerABI = [
  {
    type: 'event',
    name: 'TradeSettled',
    inputs: [
      { name: 'tradeIndex', type: 'uint256', indexed: true },
      { name: 'direction', type: 'int8', indexed: false },
      { name: 'pnl', type: 'int256', indexed: false },
      { name: 'entryPrice', type: 'uint256', indexed: false },
      { name: 'exitPrice', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'FollowerTradeSettled',
    inputs: [
      { name: 'follower', type: 'address', indexed: true },
      { name: 'vault', type: 'address', indexed: true },
      { name: 'direction', type: 'int8', indexed: false },
      { name: 'entryPrice', type: 'uint256', indexed: false },
      { name: 'exitPrice', type: 'uint256', indexed: false },
      { name: 'size', type: 'uint256', indexed: false },
      { name: 'pnl', type: 'int256', indexed: false },
      { name: 'signalHash', type: 'bytes32', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'FollowerPositionOpened',
    inputs: [
      { name: 'follower', type: 'address', indexed: true },
      { name: 'direction', type: 'int8', indexed: false },
      { name: 'entryPrice', type: 'uint256', indexed: false },
      { name: 'size', type: 'uint256', indexed: false },
      { name: 'signalHash', type: 'bytes32', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'DrawdownUpdated',
    inputs: [
      { name: 'vault', type: 'address', indexed: true },
      { name: 'currentDrawdownBps', type: 'uint256', indexed: false },
      { name: 'maxDrawdownBps', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'function',
    name: 'openFollowerPositions',
    inputs: [{ name: '', type: 'address' }],
    outputs: [
      {
        name: '',
        type: 'tuple',
        components: [
          { name: 'direction', type: 'int8' },
          { name: 'entryPrice', type: 'uint256' },
          { name: 'exitPrice', type: 'uint256' },
          { name: 'size', type: 'uint256' },
          { name: 'pnl', type: 'int256' },
          { name: 'signalHash', type: 'bytes32' },
          { name: 'timestamp', type: 'uint256' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'stats',
    inputs: [],
    outputs: [
      { name: 'totalPnl', type: 'int256' },
      { name: 'totalTrades', type: 'uint256' },
      { name: 'winCount', type: 'uint256' },
      { name: 'lossCount', type: 'uint256' },
      { name: 'highWaterMark', type: 'int256' },
      { name: 'maxDrawdownBps', type: 'uint256' },
      { name: 'currentDrawdownBps', type: 'uint256' },
      { name: 'sumReturns', type: 'int256' },
      { name: 'sumSquaredReturns', type: 'int256' },
      { name: 'lastSettledEpoch', type: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getWinRate',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getSharpeApprox',
    inputs: [],
    outputs: [{ name: '', type: 'int256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getTradeHistory',
    inputs: [
      { name: 'offset', type: 'uint256' },
      { name: 'limit', type: 'uint256' },
    ],
    outputs: [
      {
        name: '',
        type: 'tuple[]',
        components: [
          { name: 'direction', type: 'int8' },
          { name: 'entryPrice', type: 'uint256' },
          { name: 'exitPrice', type: 'uint256' },
          { name: 'size', type: 'uint256' },
          { name: 'pnl', type: 'int256' },
          { name: 'timestamp', type: 'uint256' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getFollowerTradeHistory',
    inputs: [
      { name: 'follower', type: 'address' },
      { name: 'offset', type: 'uint256' },
      { name: 'limit', type: 'uint256' },
    ],
    outputs: [
      {
        name: '',
        type: 'tuple[]',
        components: [
          { name: 'direction', type: 'int8' },
          { name: 'entryPrice', type: 'uint256' },
          { name: 'exitPrice', type: 'uint256' },
          { name: 'size', type: 'uint256' },
          { name: 'pnl', type: 'int256' },
          { name: 'signalHash', type: 'bytes32' },
          { name: 'timestamp', type: 'uint256' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getFollowerTradeCount',
    inputs: [{ name: 'follower', type: 'address' }],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getTradeCount',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
] as const;
