export const strategyVaultAbi = [
  {
    type: 'function',
    name: 'orchestrator',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'mirrorReactor',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'eventRouter',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'executionRouter',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'instrumentType',
    inputs: [],
    outputs: [{ name: '', type: 'uint8' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'sourceType',
    inputs: [],
    outputs: [{ name: '', type: 'uint8' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'sourceWallet',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'relayer',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'signalPrice',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'paymentToken',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getCurrentSignal',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'tuple',
        components: [
          { name: 'direction', type: 'int8' },
          { name: 'sizeBps', type: 'uint16' },
          { name: 'marketId', type: 'bytes32' },
          { name: 'limitPrice', type: 'uint256' },
          { name: 'epoch', type: 'uint256' },
          { name: 'reasoningHash', type: 'bytes32' },
          { name: 'reasoningSummary', type: 'string' },
        ],
      },
    ],
    stateMutability: 'view',
  },
] as const

export const externalSignalPublisherAbi = [
  {
    type: 'function',
    name: 'isCustomPublisher',
    inputs: [],
    outputs: [{ name: '', type: 'bool' }],
    stateMutability: 'pure',
  },
  {
    type: 'function',
    name: 'publish',
    inputs: [
      { name: 'direction', type: 'int8' },
      { name: 'sizeBps', type: 'uint16' },
      { name: 'marketId', type: 'bytes32' },
      { name: 'limitPrice', type: 'uint256' },
      { name: 'reason', type: 'string' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
] as const
